language: java
sudo: false
jdk:
- openjdk13
install: true
script:
- "./mvnw clean install"
before_install:
- openssl aes-256-cbc -K $encrypted_a74ed35aa1ee_key -iv $encrypted_a74ed35aa1ee_iv
  -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
after_success:
- ".travis/deploy.sh"
addons:
  ssh_known_hosts:
  - 15.188.32.86
